server:
  port: 8083




spring:
  cloud:
    gateway:
      routes:
      - id: CITIZEN-SERVICES
        uri: 
          http://localhost:8081/
        predicates:
        - Path=/citizen/**
        
      - id: VACCINATION-CENTER-SERVICES
        uri: 
          http://localhost:8082/
        predicates:
        - Path=/vaccinationcenter/**
  application:
    name: API-GATEWAY
   
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
